## Server
server:
  port: 8080
  servlet:
    context-path: /api

## Spring
spring:
  profiles:
    active: local
    include:
      - oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

redirect-url: http://localhost:8080/api/auth


## Logging
logging:
  level:
    com.glenn.socialprac: debug
    org.hibernate.SQL: debug

## JWT
jwt:
  header: Authorization
  secret: glenn-social-prac-backend-api-server-secreT1@#
  token-validity-in-seconds: 3600000
